import { DevtoolsProvider } from "@providers/devtools";
import { useNotificationProvider } from "@refinedev/antd";
import { GitHubBanner, Refine } from "@refinedev/core";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import routerProvider from "@refinedev/nextjs-router";
import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";

import { AntdRegistry } from "@ant-design/nextjs-registry";
import { AppIcon } from "@components/app-icon";
import { ColorModeContextProvider } from "@contexts/color-mode";
import { authProvider } from "@providers/auth-provider";
import { dataProvider } from "@providers/data-provider";
import "@refinedev/antd/dist/reset.css";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";

  return (
    <html lang="en">
      <body>
        <Suspense>
          <RefineKbarProvider>
            <AntdRegistry>
              <ColorModeContextProvider defaultMode={defaultMode}>
                <DevtoolsProvider>
                  <Refine
                    routerProvider={routerProvider}
                    dataProvider={dataProvider}
                    notificationProvider={useNotificationProvider}
                    authProvider={authProvider}
                    resources={[
                      {
                        name: "users",
                        list: "/users",
                        create: "/users/create",
                        edit: "/users/edit/:id",
                        show: "/users/show/:id",
                        meta: {
                          canDelete: true,
                        },
                      },
                      {
                        name: "campaigns",
                        list: "/campaigns",
                        create: "/campaigns/create",
                        edit: "/campaigns/edit/:id",
                        show: "/campaigns/show/:id",
                        meta: {
                          canDelete: true,
                        },
                      },
                      {
                        name: "creators",
                        list: "/creators",
                        create: "/creators/create",
                        edit: "/creators/edit/:id",
                        show: "/creators/show/:id",
                        meta: {
                          canDelete: true,
                        },
                      },
                      {
                        name: "social-networks",
                        list: "/social-networks",
                        create: "/social-networks/create",
                        edit: "/social-networks/edit/:id",
                        show: "/social-networks/show/:id",
                        meta: {
                          canDelete: true,
                          label: "Social Networks",
                        },
                      },
                      {
                        name: "posts-pack",
                        list: "/posts-pack",
                        create: "/posts-pack/create",
                        edit: "/posts-pack/edit/:id",
                        show: "/posts-pack/show/:id",
                        meta: {
                          canDelete: true,
                          label: "Posts Pack",
                        },
                      },
                      {
                        name: "posts",
                        list: "/posts",
                        create: "/posts/create",
                        edit: "/posts/edit/:id",
                        show: "/posts/show/:id",
                        meta: {
                          canDelete: true,
                        },
                      },
                    ]}
                    options={{
                      syncWithLocation: true,
                      warnWhenUnsavedChanges: true,
                      useNewQueryKeys: true,
                      projectId: "2ydgcl-2XAWEu-ynT0dW",
                      title: { text: "Bee Dash Admin", icon: <AppIcon /> },
                    }}
                  >
                    {children}
                    <RefineKbar />
                  </Refine>
                </DevtoolsProvider>
              </ColorModeContextProvider>
            </AntdRegistry>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}
